/** İndeks 36–100 (65 şəhər) — tip `missionGermanCities.ts`-də. */
export const MISSION_CITIES_INDEX_36_100 = [
  { name: 'Bamberg', emoji: '🍺', nickname: 'Tüstülənmiş pivə şəhəri', funFact: 'UNESCO-nun miras siyahısındadır' },
  { name: 'Bayreuth', emoji: '🎼', nickname: 'Vaqner şəhəri', funFact: 'Riçard Vaqnerin festival şəhəri' },
  { name: 'Passau', emoji: '🌊', nickname: '3 çay şəhəri', funFact: '3 çayın qovuşduğu yer' },
  { name: 'Ulm', emoji: '⛪', nickname: 'Ən hündür kilsə', funFact: 'Dünyanın ən hündür kilsə qülləsi' },
  { name: 'Rothenburg', emoji: '🏘️', nickname: 'Orta əsr şəhəri', funFact: 'Zamanın dayandığı şəhər' },
  { name: 'Stralsund', emoji: '🌅', nickname: 'Baltik şəhəri', funFact: 'UNESCO miras şəhəri' },
  { name: 'Greifswald', emoji: '🎓', nickname: 'Universitet şəhəri', funFact: '1456-cı ildən universitet var' },
  { name: 'Schwerin', emoji: '🏰', nickname: 'Göl qalası', funFact: 'Su üzərindəki nağıl qalası' },
  { name: 'Wismar', emoji: '⚓', nickname: 'Hanza şəhəri', funFact: 'Orta əsr ticarət şəhəri' },
  { name: 'Magdeburg', emoji: '⚙️', nickname: 'Mühəndislik şəhəri', funFact: 'Otto von Querickenin vətəni' },
  { name: 'Halle', emoji: '🎵', nickname: 'Handel şəhəri', funFact: 'Georq Fridrix Hendelin vətəni' },
  { name: 'Dessau', emoji: '🎨', nickname: 'Bauhaus şəhəri', funFact: 'Bauhaus dizayn məktəbinin vətəni' },
  { name: 'Weimar', emoji: '📚', nickname: 'Goethe şəhəri', funFact: 'Goethe və Şillerin şəhəri' },
  { name: 'Göttingen', emoji: '🔭', nickname: 'Elm şəhəri', funFact: '45 Nobel mükafatçısı buradan' },
  { name: 'Braunschweig', emoji: '🦁', nickname: 'Şir şəhəri', funFact: 'Henrix Şirin şəhəri' },
  { name: 'Osnabrück', emoji: '☮️', nickname: 'Sülh şəhəri', funFact: 'Vestfaliya sülhü burada imzalanıb' },
  { name: 'Bielefeld', emoji: '❓', nickname: 'Sirli şəhər', funFact: 'İnternetdə «mövcud deyil» deyilən şəhər' },
  { name: 'Paderborn', emoji: '⛲', nickname: 'Bulaq şəhəri', funFact: '100-dən çox bulağı var' },
  { name: 'Siegen', emoji: '⚒️', nickname: 'Dəmir şəhəri', funFact: 'Rubens burada anadan olub' },
  { name: 'Tübingen', emoji: '🎓', nickname: 'Tələbə şəhəri', funFact: 'Hegel və Şelling burada oxuyub' },
  { name: 'Reutlingen', emoji: '🏔️', nickname: 'Dağ şəhəri', funFact: 'Alb dağlarının ətəyindədir' },
  { name: 'Pforzheim', emoji: '💍', nickname: 'Zinət şəhəri', funFact: 'Almaniyada zərgərlik mərkəzi' },
  { name: 'Offenburg', emoji: '🍇', nickname: 'Üzüm şəhəri', funFact: 'Qara meşənin girişi' },
  { name: 'Kaiserslautern', emoji: '⚽', nickname: 'Futbol şəhəri', funFact: 'Fritz Walter stadionunun şəhəri' },
  { name: 'Koblenz', emoji: '🏰', nickname: 'Qala şəhəri', funFact: 'Reyn və Mozelin qovuşduğu yer' },
  { name: 'Saarbrücken', emoji: '🌍', nickname: 'Sərhəd şəhəri', funFact: 'Fransa ilə sərhəddə yerləşir' },
  { name: 'Bremerhaven', emoji: '🚢', nickname: 'Gəmi şəhəri', funFact: 'Böyük gəmi muzeyinə malikdir' },
  { name: 'Oldenburg', emoji: '🐴', nickname: 'At şəhəri', funFact: 'Oldenburq atı məşhurdur' },
  { name: 'Wolfsburg', emoji: '🚗', nickname: 'VW şəhəri', funFact: 'Volkswagen burada istehsal olunur' },
  { name: 'Salzgitter', emoji: '⚙️', nickname: 'Polad şəhəri', funFact: 'Alman polad sənayesinin mərkəzi' },
  { name: 'Hildesheim', emoji: '🌹', nickname: 'Gül şəhəri', funFact: '1000 illik gül ağacı var' },
  { name: 'Görlitz', emoji: '🎬', nickname: 'Kino şəhəri', funFact: 'Çox Hollywood filmi burada çəkilib' },
  { name: 'Zwickau', emoji: '🚘', nickname: 'Trabant şəhəri', funFact: 'Trabant avtomobilinin vətəni' },
  { name: 'Chemnitz', emoji: '🏭', nickname: 'Maşın şəhəri', funFact: 'Almaniyada sənaye paytaxtı' },
  { name: 'Plauen', emoji: '🧶', nickname: 'Krujeva şəhəri', funFact: 'Alman krujeva sənətinin mərkəzi' },
  { name: 'Gera', emoji: '🦩', nickname: 'Qu quşu şəhəri', funFact: 'Elster çayı boyunca uzanır' },
  { name: 'Jena', emoji: '🔬', nickname: 'Optika şəhəri', funFact: 'Zeiss linzaları burada yaranıb' },
  { name: 'Suhl', emoji: '🌲', nickname: 'Meşə şəhəri', funFact: 'Türingiya meşəsinin qəlbindədir' },
  { name: 'Eisenach', emoji: '🎹', nickname: 'Bax şəhəri', funFact: 'Yohann Sebastian Baxın vətəni' },
  { name: 'Mühlhausen', emoji: '🌾', nickname: 'Taxıl şəhəri', funFact: 'Orta əsr divarları qorunub saxlanılıb' },
  { name: 'Nordhausen', emoji: '🥃', nickname: 'Korn şəhəri', funFact: 'Alman Korn içkisinin vətəni' },
  { name: 'Quedlinburg', emoji: '📿', nickname: 'Daş şəhəri', funFact: 'UNESCO miras şəhəri' },
  { name: 'Wernigerode', emoji: '🎨', nickname: 'Rəngli şəhər', funFact: 'Harzın ən gözəl şəhəri' },
  { name: 'Halberstadt', emoji: '🎵', nickname: 'Musiqi şəhəri', funFact: '639 illik musiqi əsəri ifa olunur' },
  { name: 'Stendal', emoji: '🎭', nickname: 'Altmark şəhəri', funFact: 'Winckelmannın vətəni' },
  {
    name: 'Lutherstadt Wittenberg',
    emoji: '✝️',
    nickname: 'Reformasiya şəhəri',
    funFact: 'Martın Lüterin şəhəri',
  },
  {
    name: 'Dessau-Roßlau',
    emoji: '🌊',
    nickname: 'Çay şəhəri',
    funFact: 'Elba və Muldenin qovuşduğu yer',
  },
  { name: 'Bitterfeld', emoji: '🌱', nickname: 'Yenilənmə şəhəri', funFact: 'Köhnə sənaye şəhərindən yaşıl şəhərə' },
  { name: 'Merseburg', emoji: '🐉', nickname: 'Əjdaha şəhəri', funFact: 'Merseburg sehrbazlığının vətəni' },
  { name: 'Naumburg', emoji: '🍷', nickname: 'Şərab şəhəri', funFact: 'Zaal vadisinin şərab üzümü' },
  { name: 'Zeitz', emoji: '🕰️', nickname: 'Köhnə şəhər', funFact: 'Min illik tarixə malik şəhər' },
  { name: 'Altenburg', emoji: '🃏', nickname: 'Kart oyunu şəhəri', funFact: 'Alman kart oyununun vətəni' },
  { name: 'Glauchau', emoji: '🏛️', nickname: 'Qala şəhəri', funFact: 'Çoxlu tarixi qalalara malikdir' },
  { name: 'Aue', emoji: '🎸', nickname: 'Rok şəhəri', funFact: 'Alman rok musiqisinin mərkəzi' },
  {
    name: 'Annaberg-Buchholz',
    emoji: '⛏️',
    nickname: 'Gümüş şəhəri',
    funFact: 'Köhnə gümüş mədəni şəhəri',
  },
  { name: 'Flensburg', emoji: '🇩🇰', nickname: 'Sərhəd şəhəri', funFact: 'Danimarkayla sərhəddə yerləşir' },
  { name: 'Neumünster', emoji: '🧵', nickname: 'Toxuculuq şəhəri', funFact: 'Alman toxuculuq mərkəzi' },
  { name: 'Lüneburg', emoji: '🧂', nickname: 'Duz şəhəri', funFact: 'Orta əsrlərdə duz ticarəti mərkəzi' },
  { name: 'Celle', emoji: '🐝', nickname: 'Bal şəhəri', funFact: 'Arıçılıq ənənələri ilə məşhur' },
  { name: 'Hameln', emoji: '🐀', nickname: 'Siçovul tutanın şəhəri', funFact: 'Qrimm nağılının şəhəri' },
  { name: 'Detmold', emoji: '🏹', nickname: 'Hermann şəhəri', funFact: 'Hermanın heykəli burada' },
  { name: 'Soest', emoji: '🌿', nickname: 'Yaşıl şəhər', funFact: 'Qərbi Faliyanın incisi' },
  { name: 'Iserlohn', emoji: '🗡️', nickname: 'Dəmirçi şəhəri', funFact: 'Köhnə sənətkarlıq şəhəri' },
  { name: 'Hagen', emoji: '🎨', nickname: 'İncəsənət şəhəri', funFact: 'Osthaus muzeyinin şəhəri' },
  { name: 'Wuppertal', emoji: '🚡', nickname: 'Asma tramvay şəhəri', funFact: 'Dünyanın ən qədim asma tramvayı' },
] as const;

/** İndeks 101–299 üçün real Alman şəhər adları (199). */
export const PLACEHOLDER_CITY_NAMES_101_299: readonly string[] = [
  'Bielefeld',
  'Gelsenkirchen',
  'Krefeld',
  'Wilhelmshaven',
  'Minden',
  'Delmenhorst',
  'Gladbeck',
  'Castrop-Rauxel',
  'Lünen',
  'Ratingen',
  'Velbert',
  'Rheine',
  'Troisdorf',
  'Viersen',
  'Lüdenscheid',
  'Arnsberg',
  'Bocholt',
  'Gütersloh',
  'Dülmen',
  'Iserlohn',
  'Kleve',
  'Euskirchen',
  'Hürth',
  'Kerpen',
  'Bergheim',
  'Langenfeld',
  'Frechen',
  'Pulheim',
  'Herten',
  'Unna',
  'Dormagen',
  'Völklingen',
  'Ravensburg',
  'Heidenheim',
  'Sindelfingen',
  'Böblingen',
  'Ludwigsburg',
  'Esslingen',
  'Tübingen',
  'Rastatt',
  'Lörrach',
  'Offenburg',
  'Lahr',
  'Achern',
  'Bruchsal',
  'Ettlingen',
  'Bühl',
  'Kehl',
  'Rüsselsheim',
  'Hanau',
  'Miltenberg',
  'Schweinfurt',
  'Coburg',
  'Freiberg',
  'Bautzen',
  'Hoyerswerda',
  'Eberswalde',
  'Neuruppin',
  'Rathenow',
  'Stendal',
  'Salzwedel',
  'Uelzen',
  'Gifhorn',
  'Helmstedt',
  'Northeim',
  'Einbeck',
  'Rinteln',
  'Bückeburg',
  'Herford',
  'Lemgo',
  'Witten',
  'Hattingen',
  'Schwelm',
  'Gevelsberg',
  'Sprockhövel',
  'Ennepetal',
  'Kamen',
  'Bergkamen',
  'Selm',
  'Olfen',
  'Coesfeld',
  'Steinfurt',
  'Emsdetten',
  'Greven',
  'Telgte',
  'Warendorf',
  'Beckum',
  'Ahlen',
  'Werne',
  'Haltern',
  'Kamp-Lintfort',
  'Rheinberg',
  'Xanten',
  'Geldern',
  'Emmerich',
  'Rees',
  'Isselburg',
  'Ahaus',
  'Gronau',
  'Nordhorn',
  'Meppen',
  'Papenburg',
  'Leer',
  'Emden',
  'Jever',
  'Wittmund',
  'Aurich',
  'Norden',
  'Esens',
  'Brake',
  'Stade',
  'Cuxhaven',
  'Verden',
  'Rotenburg',
  'Soltau',
  'Walsrode',
  'Nienburg',
  'Springe',
  'Barsinghausen',
  'Garbsen',
  'Seelze',
  'Wunstorf',
  'Burgdorf',
  'Peine',
  'Salzgitter',
  'Sondershausen',
  'Heilbad Heiligenstadt',
  'Sommerda',
  'Naumburg',
  'Merseburg',
  'Bitterfeld',
  'Bernburg',
  'Staßfurt',
  'Aschersleben',
  'Blankenburg',
  'Thale',
  'Ballenstedt',
  'Crailsheim',
  'Schwetzingen',
  'Hockenheim',
  'Weinheim',
  'Singen',
  'Friedrichshafen',
  'Lindau',
  'Memmingen',
  'Kempten',
  'Rosenheim',
  'Traunreut',
  'Erding',
  'Starnberg',
  'Germering',
  'Freising',
  'Neumarkt',
  'Amberg',
  'Weiden',
  'Schwandorf',
  'Kelheim',
  'Cham',
  'Schwabach',
  'Herzogenaurach',
  'Pirmasens',
  'Zweibrücken',
  'Neuwied',
  'Andernach',
  'Remagen',
  'Königswinter',
  'Hennef',
  'Siegburg',
  'Sankt Augustin',
  'Brühl',
  'Erftstadt',
  'Cloppenburg',
  'Vechta',
  'Diepholz',
  'Syke',
  'Winsen',
  'Stuhr',
  'Achim',
  'Seevetal',
  'Buchholz',
  'Pinneberg',
  'Wedel',
  'Ahrensburg',
  'Reinbek',
  'Geesthacht',
  'Schwarzenbek',
  'Mölln',
  'Ratzeburg',
  'Eutin',
  'Neumünster',
  'Itzehoe',
  'Elmshorn',
  'Quickborn',
  'Kaltenkirchen',
  'Henstedt-Ulzburg',
  'Norderstedt',
  'Bad Homburg',
  'Metzingen',
  'Löbau',
];
