/**
 * Sözlər bazası — A1 və A2 səviyyələri.
 * VOCAB_BASE.A1 / VOCAB_BASE.A2 — substantivlər və fe'llər edatlarla.
 * Substantivlər: [ artıqlı (Der/Die/Das), isim, azərbaycanca tərcümə ]
 * Fe'llər: [ fe'l, edat, hal (Akkusativ/Dativ), azərbaycanca tərcümə ]
 */
const VOCAB_BASE = {
  A1: {
  nouns: [
    ['Das', 'Haus', 'Ev'],
    ['Das', 'Wasser', 'Su'],
    ['Das', 'Brot', 'Çörək'],
    ['Die', 'Mutter', 'Ana'],
    ['Der', 'Vater', 'Ata'],
    ['Das', 'Kind', 'Uşaq'],
    ['Der', 'Tag', 'Gün'],
    ['Die', 'Nacht', 'Gecə'],
    ['Das', 'Buch', 'Kitab'],
    ['Die', 'Schule', 'Məktəb'],
    ['Das', 'Essen', 'Yemək'],
    ['Der', 'Freund', 'Dost'],
    ['Die', 'Arbeit', 'İş'],
    ['Das', 'Jahr', 'İl'],
    ['Die', 'Zeit', 'Vaxt'],
    ['Der', 'Mann', 'Kişi'],
    ['Die', 'Frau', 'Qadın'],
    ['Die', 'Stadt', 'Şəhər'],
    ['Das', 'Land', 'Ölkə'],
    ['Der', 'Morgen', 'Səhər'],
    ['Der', 'Abend', 'Axşam'],
    ['Die', 'Woche', 'Həftə'],
    ['Der', 'Monat', 'Ay'],
    ['Die', 'Stunde', 'Saat'],
    ['Die', 'Minute', 'Dəqiqə'],
    ['Der', 'Weg', 'Yol'],
    ['Die', 'Straße', 'Küçə'],
    ['Das', 'Zimmer', 'Otaq'],
    ['Die', 'Tür', 'Qapı'],
    ['Das', 'Fenster', 'Pəncərə'],
    ['Der', 'Tisch', 'Stol'],
    ['Der', 'Stuhl', 'Stul'],
    ['Das', 'Bett', 'Çarpayı'],
    ['Die', 'Küche', 'Mətbəx'],
    ['Das', 'Badezimmer', 'Vanna otağı'],
    ['Die', 'Toilette', 'Tualet'],
    ['Der', 'Schlüssel', 'Açar'],
    ['Das', 'Geld', 'Pul'],
    ['Die', 'Tasche', 'Çanta'],
    ['Der', 'Koffer', 'Çamadan'],
    ['Die', 'Uhr', 'Saat'],
    ['Das', 'Handy', 'Mobil telefon'],
    ['Der', 'Computer', 'Kompüter'],
    ['Die', 'Zeitung', 'Qəzet'],
    ['Der', 'Brief', 'Məktub'],
    ['Die', 'Post', 'Poçt'],
    ['Das', 'Auto', 'Avtomobil'],
    ['Der', 'Bus', 'Avtobus'],
    ['Die', 'Bahn', 'Qatar'],
    ['Der', 'Zug', 'Qatar'],
    ['Der', 'Flughafen', 'Hava limanı'],
    ['Der', 'Bahnhof', 'Vağzal'],
    ['Die', 'Apotheke', 'Aptek'],
    ['Der', 'Markt', 'Bazar'],
    ['Das', 'Geschäft', 'Mağaza'],
    ['Die', 'Bank', 'Bank'],
    ['Der', 'Park', 'Park'],
    ['Die', 'Kirche', 'Kilsə'],
    ['Das', 'Museum', 'Muzey'],
    ['Die', 'Universität', 'Universitet'],
    ['Der', 'Lehrer', 'Müəllim'],
    ['Die', 'Lehrerin', 'Müəllimə'],
    ['Der', 'Arzt', 'Həkim'],
    ['Die', 'Ärztin', 'Həkim (qadın)'],
    ['Der', 'Student', 'Tələbə'],
    ['Die', 'Studentin', 'Tələbə (qadın)'],
    ['Das', 'Obst', 'Meyvə'],
    ['Das', 'Gemüse', 'Tərəvəz'],
    ['Das', 'Fleisch', 'Ət'],
    ['Die', 'Milch', 'Süd'],
    ['Der', 'Käse', 'Pendir'],
    ['Das', 'Ei', 'Yumurta'],
    ['Der', 'Kaffee', 'Qəhvə'],
    ['Der', 'Tee', 'Çay'],
    ['Das', 'Bier', 'Piva'],
    ['Der', 'Wein', 'Şərab'],
    ['Die', 'Butter', 'Yağ'],
    ['Das', 'Salz', 'Duz'],
    ['Der', 'Zucker', 'Şəkər'],
    ['Die', 'Suppe', 'Şorba'],
    ['Der', 'Salat', 'Salat'],
    ['Die', 'Pizza', 'Pitsa'],
    ['Der', 'Kuchen', 'Tort'],
    ['Die', 'Schokolade', 'Şokolad'],
    ['Der', 'Körper', 'Bədən'],
    ['Der', 'Kopf', 'Baş'],
    ['Das', 'Auge', 'Göz'],
    ['Das', 'Ohr', 'Qulaq'],
    ['Die', 'Nase', 'Burun'],
    ['Der', 'Mund', 'Ağız'],
    ['Die', 'Hand', 'Əl'],
    ['Der', 'Finger', 'Barmaq'],
    ['Der', 'Fuß', 'Ayaq'],
    ['Das', 'Bein', 'Ayaq / Qıç'],
    ['Der', 'Rücken', 'Bel'],
    ['Die', 'Familie', 'Ailə'],
    ['Der', 'Bruder', 'Qardaş'],
    ['Die', 'Schwester', 'Bacı'],
    ['Der', 'Sohn', 'Oğul'],
    ['Die', 'Tochter', 'Qız'],
    ['Der', 'Opa', 'Baba'],
    ['Die', 'Oma', 'Nənə'],
    ['Der', 'Enkel', 'Nəvə'],
    ['Die', 'Enkelin', 'Nəvə (qadın)'],
    ['Der', 'Hund', 'İt'],
    ['Die', 'Katze', 'Pişik'],
    ['Das', 'Tier', 'Heyvan'],
    ['Der', 'Vogel', 'Quş'],
    ['Die', 'Blume', 'Çiçək'],
    ['Der', 'Baum', 'Ağac'],
    ['Das', 'Wetter', 'Hava'],
    ['Die', 'Sonne', 'Günəş'],
    ['Der', 'Regen', 'Yağış'],
    ['Der', 'Schnee', 'Qar'],
    ['Der', 'Wind', 'Külək'],
    ['Die', 'Natur', 'Təbiət'],
    ['Das', 'Problem', 'Problem'],
    ['Die', 'Frage', 'Sual'],
    ['Die', 'Antwort', 'Cavab'],
    ['Der', 'Name', 'Ad'],
    ['Die', 'Adresse', 'Ünvan'],
    ['Die', 'Nummer', 'Nömrə'],
    ['Der', 'Preis', 'Qiymət'],
    ['Die', 'Rechnung', 'Hesab'],
    ['Das', 'Datum', 'Tarix'],
    ['Der', 'Geburtstag', 'Ad günü'],
    ['Das', 'Geschenk', 'Hədiyyə'],
    ['Der', 'Urlaub', 'Tətil'],
    ['Die', 'Reise', 'Səyahət'],
    ['Der', 'Pass', 'Pasport'],
    ['Das', 'Formular', 'Forma'],
    ['Die', 'Sprache', 'Dil'],
    ['Das', 'Wort', 'Söz'],
    ['Der', 'Satz', 'Cümlə'],
    ['Die', 'Grammatik', 'Qrammatika'],
    ['Der', 'Fehler', 'Səhv'],
    ['Die', 'Prüfung', 'İmtahan'],
    ['Das', 'Ergebnis', 'Nəticə'],
    ['Der', 'Anfang', 'Başlanğıc'],
    ['Das', 'Ende', 'Son'],
    ['Der', 'Teil', 'Hissə'],
    ['Die', 'Möglichkeit', 'İmkan'],
    ['Der', 'Grund', 'Səbəb'],
    ['Die', 'Idee', 'Fikir'],
    ['Der', 'Plan', 'Plan'],
    ['Die', 'Zeitschrift', 'Jurnal'],
    ['Der', 'Film', 'Film'],
    ['Die', 'Musik', 'Musiqi'],
    ['Das', 'Lied', 'Mahnı'],
    ['Der', 'Sport', 'İdman'],
    ['Das', 'Spiel', 'Oyun'],
    ['Der', 'Ball', 'Top'],
    ['Die', 'Party', 'Parti'],
    ['Der', 'Gast', 'Qonaq'],
    ['Die', 'Einladung', 'Dəvət'],
    ['Der', 'Termin', 'Görüş'],
    ['Die', 'Pause', 'Fasilə'],
    ['Der', 'Job', 'İş'],
    ['Die', 'Firma', 'Şirkət'],
    ['Der', 'Chef', 'Rəhbər'],
    ['Die', 'Kollegin', 'Əməkdaş (qadın)'],
    ['Der', 'Kollege', 'Əməkdaş'],
    ['Das', 'Gehalt', 'Maaş'],
    ['Die', 'Versicherung', 'Sığorta'],
    ['Der', 'Vertrag', 'Müqavilə'],
    ['Die', 'Karte', 'Kart'],
    ['Der', 'Führerschein', 'Sürücülük vəsiqəsi'],
    ['Das', 'Benzin', 'Benzin'],
    ['Die', 'Reparatur', 'Təmir'],
    ['Der', 'Notfall', 'Təcili hal'],
    ['Die', 'Polizei', 'Polis'],
    ['Der', 'Krankenwagen', 'Təcili yardım'],
    ['Das', 'Medikament', 'Dərman'],
    ['Die', 'Krankheit', 'Xəstəlik'],
    ['Der', 'Schmerz', 'Ağrı'],
    ['Das', 'Fieber', 'Qızdırma'],
    ['Die', 'Allergie', 'Allergiya'],
    ['Die', 'Klinik', 'Klinika'],
    ['Der', 'Notruf', 'Təcili xidmət'],
    ['Das', 'Leben', 'Həyat'],
    ['Der', 'Tod', 'Ölüm'],
    ['Die', 'Liebe', 'Sevgi'],
    ['Der', 'Traum', 'Yuxu'],
    ['Die', 'Hoffnung', 'Ümid'],
    ['Der', 'Wunsch', 'Arzu'],
    ['Die', 'Angst', 'Qorxu'],
    ['Der', 'Stress', 'Stress'],
    ['Die', 'Ruhe', 'Sakitlik'],
    ['Das', 'Glück', 'Bəxt'],
    ['Der', 'Kummer', 'Kədər'],
    ['Die', 'Freude', 'Sevinc'],
    ['Der', 'Lärm', 'Səs-küy'],
    ['Die', 'Stille', 'Səssizlik'],
    ['Das', 'Licht', 'İşıq'],
    ['Der', 'Schatten', 'Kölgə'],
    ['Die', 'Farbe', 'Rəng'],
    ['Der', 'Geruch', 'Qoxu'],
    ['Der', 'Geschmack', 'Dad'],
    ['Die', 'Größe', 'Ölçü'],
    ['Das', 'Gewicht', 'Çəki'],
    ['Der', 'Raum', 'Məkan'],
    ['Die', 'Ecke', 'Künc'],
    ['Das', 'Zentrum', 'Mərkəz'],
    ['Der', 'Norden', 'Şimal'],
    ['Der', 'Süd', 'Cənub'],
    ['Der', 'Osten', 'Şərq'],
    ['Der', 'Westen', 'Qərb'],
    ['Die', 'Grenze', 'Sərhəd'],
    ['Der', 'Nachbar', 'Qonşu'],
    ['Die', 'Nachbarin', 'Qonşu (qadın)'],
    ['Das', 'Dorf', 'Kənd'],
    ['Die', 'Region', 'Region'],
    ['Der', 'Fluss', 'Çay'],
    ['Der', 'See', 'Göl'],
    ['Das', 'Meer', 'Dəniz'],
    ['Der', 'Berg', 'Dağ'],
    ['Der', 'Wald', 'Meşə'],
    ['Das', 'Feld', 'Sahə'],
    ['Die', 'Insel', 'Ada'],
    ['Der', 'Strand', 'Çimərlik'],
    ['Das', 'Hotel', 'Otel'],
    ['Die', 'Reservation', 'Rezervasiya'],
    ['Der', 'Empfang', 'Qəbul'],
    ['Die', 'Rezeption', 'Resepsiya'],
    ['Der', 'Aufzug', 'Lift'],
    ['Die', 'Treppe', 'Nərdivan'],
    ['Das', 'Dach', 'Dam'],
    ['Der', 'Keller', 'Zirzəmi'],
    ['Der', 'Balkon', 'Balkon'],
    ['Der', 'Garten', 'Bağ'],
    ['Die', 'Garage', 'Qaraj'],
    ['Das', 'Regal', 'Rəf'],
    ['Die', 'Lampe', 'Lampa'],
    ['Der', 'Stecker', 'Şteker'],
    ['Die', 'Steckdose', 'Rozetka'],
    ['Der', 'Hahn', 'Kran'],
    ['Die', 'Seife', 'Sabun'],
    ['Das', 'Handtuch', 'Dəsmal'],
    ['Die', 'Zahnbürste', 'Diş fırçası'],
    ['Die', 'Zahnpasta', 'Diş pastası'],
    ['Der', 'Kamm', 'Daraq'],
    ['Der', 'Spiegel', 'Güzgü'],
    ['Die', 'Creme', 'Krem'],
    ['Das', 'Shampoo', 'Şampun'],
    ['Der', 'Wecker', 'Zəng'],
    ['Die', 'Decke', 'Yorğan'],
    ['Das', 'Kissen', 'Yastıq'],
    ['Der', 'Schrank', 'Şkaf'],
    ['Die', 'Schublade', 'Siyirmə'],
    ['Das', 'Sofa', 'Divan'],
    ['Die', 'Couch', 'Divan'],
    ['Der', 'Fernseher', 'Televizor'],
    ['Die', 'Fernbedienung', 'Məsafədən idarəetmə pultu'],
    ['Der', 'Laptop', 'Noutbuk'],
    ['Die', 'Tastatur', 'Klaviatura'],
    ['Die', 'Maus', 'Siçan (kompüter)'],
    ['Der', 'Bildschirm', 'Ekran'],
    ['Das', 'Internet', 'İnternet'],
    ['Die', 'E-Mail', 'E-poçt'],
    ['Der', 'Anruf', 'Zəng'],
    ['Die', 'Nachricht', 'Mesaj'],
    ['Der', 'Kalender', 'Təqvim'],
    ['Die', 'Liste', 'Siyahı'],
    ['Der', 'Stift', 'Qələm'],
    ['Das', 'Papier', 'Kağız'],
    ['Die', 'Schere', 'Qayçı'],
    ['Der', 'Kleber', 'Yapışqan'],
    ['Das', 'Heft', 'Dəftər'],
    ['Die', 'Schultasche', 'Məktəb çantası'],
    ['Der', 'Rucksack', 'Sırt çantası'],
    ['Die', 'Brille', 'Eynək'],
    ['Der', 'Regenschirm', 'Çətir'],
    ['Die', 'Jacke', 'Ceket'],
    ['Der', 'Mantel', 'Palto'],
    ['Das', 'Hemd', 'Köynək'],
    ['Die', 'Hose', 'Şalvar'],
    ['Der', 'Rock', 'Yubka'],
    ['Das', 'Kleid', 'Paltar'],
    ['Der', 'Schuh', 'Ayaqqabı'],
    ['Die', 'Socke', 'Corab'],
    ['Der', 'Handschuh', 'Əlcək'],
    ['Der', 'Schal', 'Şərf'],
    ['Die', 'Mütze', 'Şapka'],
    ['Der', 'Hut', 'Şapka'],
    ['Das', 'Kleidungsstück', 'Geyim'],
    ['Die', 'Waschmaschine', 'Paltaryuyan'],
    ['Der', 'Trockner', 'Quruducu'],
    ['Das', 'Bügeleisen', 'Ütü'],
    ['Die', 'Nadel', 'İynə'],
    ['Der', 'Faden', 'İp'],
    ['Die', 'Nähmaschine', 'Tikiş maşını'],
    ['Der', 'Knopf', 'Düymə'],
    ['Der', 'Reißverschluss', 'İldirəm'],
    ['Die', 'Tasche', 'Cib'],
    ['Der', 'Gürtel', 'Kəmər'],
    ['Das', 'Portemonnaie', 'Pul kisəsi'],
    ['Die', 'Sonnenbrille', 'Günəş eynəyi'],
    ['Der', 'Schmuck', 'Zinət'],
    ['Die', 'Uhr', 'Saat (bilərzik)'],
    ['Der', 'Ring', 'Üzük'],
    ['Die', 'Kette', 'Zəncir'],
    ['Der', 'Ohrring', 'Sırğa'],
    ['Die', 'Landkarte', 'Xəritə'],
    ['Der', 'Reiseführer', 'Səyahət bələdçisi'],
    ['Das', 'Visum', 'Viza'],
    ['Die', 'Impfung', 'Peyvənd'],
    ['Der', 'Impfpass', 'Peyvənd pasportu'],
    ['Das', 'Gepäck', 'Yük'],
    ['Die', 'Ankunft', 'Gəliş'],
    ['Der', 'Abflug', 'Uçuş'],
    ['Die', 'Landung', 'Eniş'],
    ['Der', 'Sitz', 'Oturacaq'],
    ['Die', 'Reihe', 'Sıra'],
    ['Der', 'Platz', 'Yer'],
    ['Die', 'Reservierung', 'Rezervasiya'],
    ['Der', 'Gang', 'Koridor'],
    ['Die', 'Toilette', 'Tualet'],
    ['Der', 'Notausgang', 'Fövqəladə çıxış'],
    ['Die', 'Sicherheit', 'Təhlükəsizlik'],
    ['Der', 'Kontrolle', 'Nəzarət'],
    ['Das', 'Gepäck', 'Baqaj'],
    ['Die', 'Abfertigung', 'Rəsmiləşdirmə'],
    ['Der', 'Zoll', 'Gömrük'],
    ['Die', 'Deklaration', 'Bəyannamə'],
    ['Die', 'Handtasche', 'Əl çantası'],
    ['Das', 'Gepäckstück', 'Baqaj əşyası'],
    ['Der', 'Fahrplan', 'Cədvəl'],
    ['Die', 'Verspätung', 'Gecikmə'],
    ['Der', 'Anschluss', 'Keçid'],
    ['Die', 'Umsteigen', 'Transfer'],
    ['Der', 'Gleis', 'Perron'],
    ['Die', 'Haltestelle', 'Dayanacaq'],
    ['Der', 'Fahrschein', 'Bilet'],
    ['Die', 'Fahrkarte', 'Bilet'],
    ['Der', 'Schaffner', 'Konduktor'],
    ['Die', 'Fahrt', 'Səfər'],
    ['Der', 'Stau', 'Tıxac'],
    ['Die', 'Autobahn', 'Avtomobil yolu'],
    ['Der', 'Kreuzung', 'Çarpazlaşma'],
    ['Die', 'Ampel', 'İşıqfor'],
    ['Der', 'Fußgänger', 'Piyada'],
    ['Die', 'Fußgängerzone', 'Piyada zonası'],
    ['Der', 'Parkplatz', 'Park yeri'],
    ['Die', 'Tankstelle', 'Benzin doldurma məntəqəsi'],
    ['Der', 'Unfall', 'Qəza'],
    ['Die', 'Verletzung', 'Yaralanma'],
    ['Das', 'Krankenhaus', 'Xəstəxana'],
    ['Die', 'Rettung', 'Xilasetmə'],
    ['Die', 'Krankenschwester', 'Tibb bacısı'],
    ['Der', 'Patient', 'Xəstə'],
    ['Die', 'Behandlung', 'Müalicə'],
    ['Das', 'Rezept', 'Rezept'],
    ['Die', 'Tablette', 'Tablet'],
    ['Der', 'Sirup', 'Şərbət'],
    ['Die', 'Spritze', 'İynə'],
    ['Der', 'Verband', 'Sargı'],
    ['Die', 'Wunde', 'Yara'],
    ['Das', 'Pflaster', 'Yara bantı'],
    ['Die', 'Sprechstunde', 'Qəbul saatı'],
    ['Der', 'Wartezimmer', 'Gözləmə otağı'],
    ['Die', 'Krankenversicherung', 'Səhiyyə sığortası'],
    ['Der', 'Impfstoff', 'Peyvənd maddəsi'],
    ['Die', 'Dosis', 'Doza'],
    ['Der', 'Nebenwirkung', 'Yan təsir'],
    ['Die', 'Allergie', 'Allergiya'],
    ['Der', 'Schmerz', 'Ağrı'],
    ['Die', 'Kopfschmerzen', 'Baş ağrısı'],
    ['Der', 'Bauchschmerzen', 'Qarın ağrısı'],
    ['Die', 'Halsschmerzen', 'Boğaz ağrısı'],
    ['Der', 'Fieber', 'Qızdırma'],
    ['Die', 'Husten', 'Öskürək'],
    ['Der', 'Schnupfen', 'Sellək'],
    ['Die', 'Erkältung', 'Soyuqlama'],
    ['Der', 'Grippe', 'Qrip'],
    ['Die', 'Krankheit', 'Xəstəlik'],
    ['Die', 'Gesundheit', 'Sağlamlıq'],
    ['Die', 'Vorsorge', 'Qabaqcadan qayğı'],
    ['Der', 'Check-up', 'Yoxlama'],
    ['Die', 'Blutdruck', 'Qan təzyiqi'],
    ['Der', 'Puls', 'Nəbz'],
    ['Die', 'Temperatur', 'Temperatur'],
    ['Das', 'Gewicht', 'Çəki'],
    ['Die', 'Diät', 'Pəhriz'],
    ['Der', 'Sport', 'İdman'],
    ['Die', 'Bewegung', 'Hərəkət'],
    ['Der', 'Schlaf', 'Yuxu'],
    ['Die', 'Ernährung', 'Qidalanma'],
    ['Der', 'Vitamin', 'Vitamin'],
    ['Die', 'Kalorie', 'Kalori'],
    ['Der', 'Zucker', 'Şəkər'],
    ['Das', 'Salz', 'Duz'],
    ['Das', 'Fett', 'Yağ'],
    ['Der', 'Alkohol', 'Alkoqol'],
    ['Die', 'Nikotin', 'Nikotin'],
    ['Der', 'Raucher', 'Papiros çəkən'],
    ['Die', 'Raucherentwöhnung', 'Papirosdan imtina'],
    ['Der', 'Stress', 'Stress'],
    ['Die', 'Entspannung', 'Rahatlıq'],
    ['Der', 'Urlaub', 'Tətil'],
    ['Die', 'Erholung', 'Dinclik']
  ],

  verbsWithPrepositions: [
    ['warten', 'auf', 'Akkusativ', 'gözləmək'],
    ['sprechen', 'mit', 'Dativ', 'danışmaq'],
    ['denken', 'an', 'Akkusativ', 'düşünmək'],
    ['sich freuen', 'auf', 'Akkusativ', 'sevinmək (nəyəsə)'],
    ['sich freuen', 'über', 'Akkusativ', 'sevinmək (nəyəsə)'],
    ['sich erinnern', 'an', 'Akkusativ', 'xatırlamaq'],
    ['sich interessieren', 'für', 'Akkusativ', 'maraqlanmaq'],
    ['halten', 'von', 'Dativ', 'fikirdə olmaq'],
    ['träumen', 'von', 'Dativ', 'arzu etmək'],
    ['abhängen', 'von', 'Dativ', 'asılı olmaq'],
    ['erzählen', 'von', 'Dativ', 'danışmaq (haqqında)'],
    ['reden', 'über', 'Akkusativ', 'danışmaq (haqqında)'],
    ['sprechen', 'über', 'Akkusativ', 'danışmaq (haqqında)'],
    ['nachdenken', 'über', 'Akkusativ', 'düşünmək (haqqında)'],
    ['sich ärgern', 'über', 'Akkusativ', 'əsəbləşmək'],
    ['sich beschweren', 'über', 'Akkusativ', 'şikayət etmək'],
    ['lachen', 'über', 'Akkusativ', 'gülmək'],
    ['weinen', 'über', 'Akkusativ', 'ağlamaq'],
    ['wissen', 'von', 'Dativ', 'bilmək (haqqında)'],
    ['hören', 'von', 'Dativ', 'eşitmək'],
    ['lesen', 'von', 'Dativ', 'oxumaq (haqqında)'],
    ['glauben', 'an', 'Akkusativ', 'inancı olmaq'],
    ['teilnehmen', 'an', 'Dativ', 'iştirak etmək'],
    ['denken', 'an', 'Akkusativ', 'düşünmək'],
    ['schreiben', 'an', 'Akkusativ', 'yazmaq (kimsəyə)'],
    ['arbeiten', 'an', 'Dativ', 'işləmək (nəyəsə)'],
    ['sterben', 'an', 'Dativ', 'ölmək (nəyəsə)'],
    ['erkranken', 'an', 'Dativ', 'xəstələnmək'],
    ['legen', 'auf', 'Akkusativ', 'qoymaq (üstünə)'],
    ['achten', 'auf', 'Akkusativ', 'diqqət etmək'],
    ['hoffen', 'auf', 'Akkusativ', 'ümid etmək'],
    ['verzichten', 'auf', 'Akkusativ', 'vaz keçmək'],
    ['reagieren', 'auf', 'Akkusativ', 'reaksiya göstərmək'],
    ['antworten', 'auf', 'Akkusativ', 'cavab vermək'],
    ['sich vorbereiten', 'auf', 'Akkusativ', 'hazırlaşmaq'],
    ['sich konzentrieren', 'auf', 'Akkusativ', 'cəmləşmək'],
    ['sich spezialisieren', 'auf', 'Akkusativ', 'ixtisaslaşmaq'],
    ['bestehen', 'auf', 'Dativ', 'israrlı olmaq'],
    ['warten', 'auf', 'Akkusativ', 'gözləmək'],
    ['sich freuen', 'auf', 'Akkusativ', 'səbirsizliklə gözləmək'],
    ['sorgen', 'für', 'Akkusativ', 'qayğı göstərmək'],
    ['halten', 'für', 'Akkusativ', 'saxlamaq (nəyəsə)'],
    ['danken', 'für', 'Akkusativ', 'təşəkkür etmək'],
    ['entschuldigen', 'für', 'Akkusativ', 'üzr istəmək'],
    ['kämpfen', 'für', 'Akkusativ', 'mübarizə etmək'],
    ['stimmen', 'für', 'Akkusativ', 'səs vermək'],
    ['sein', 'für', 'Akkusativ', 'olmaq (tərəfdar)'],
    ['sich bedanken', 'für', 'Akkusativ', 'təşəkkür etmək'],
    ['sich entschuldigen', 'für', 'Akkusativ', 'üzr istəmək'],
    ['gehen', 'zu', 'Dativ', 'getmək (kimsəyə)'],
    ['kommen', 'zu', 'Dativ', 'gəlmək'],
    ['werden', 'zu', 'Dativ', 'çevrilmək'],
    ['gehören', 'zu', 'Dativ', 'aid olmaq'],
    ['sagen', 'zu', 'Dativ', 'demək (nəyəsə)'],
    ['meinen', 'zu', 'Dativ', 'fikir bildirmək'],
    ['raten', 'zu', 'Dativ', 'məsləhət vermək'],
    ['neigen', 'zu', 'Dativ', 'meyil göstərmək'],
    ['lachen', 'über', 'Akkusativ', 'gülmək'],
    ['reden', 'mit', 'Dativ', 'danışmaq'],
    ['sprechen', 'mit', 'Dativ', 'danışmaq'],
    ['streiten', 'mit', 'Dativ', 'dalaşmaq'],
    ['rechnen', 'mit', 'Dativ', 'güman etmək'],
    ['anfangen', 'mit', 'Dativ', 'başlamaq'],
    ['aufhören', 'mit', 'Dativ', 'dayandırmaq'],
    ['beginnen', 'mit', 'Dativ', 'başlamaq'],
    ['helfen', 'bei', 'Dativ', 'kömək etmək'],
    ['sich beschweren', 'bei', 'Dativ', 'şikayət etmək'],
    ['sich bedanken', 'bei', 'Dativ', 'təşəkkür etmək'],
    ['ankommen', 'in', 'Dativ', 'gəlmək (şəhərə)'],
    ['einsteigen', 'in', 'Akkusativ', 'minmək'],
    ['sich verlieben', 'in', 'Akkusativ', 'aşiq olmaq'],
    ['teilen', 'in', 'Akkusativ', 'bölmək'],
    ['bestehen', 'aus', 'Dativ', 'təşkil olmaq'],
    ['bestehen', 'in', 'Dativ', 'olmaq (nəyəsə)'],
    ['sich irren', 'in', 'Dativ', 'səhv etmək'],
    ['fragen', 'nach', 'Dativ', 'soruşmaq'],
    ['suchen', 'nach', 'Dativ', 'axtarmaq'],
    ['schauen', 'nach', 'Dativ', 'baxmaq'],
    ['riechen', 'nach', 'Dativ', 'iylənmək'],
    ['kommen', 'aus', 'Dativ', 'gəlmək (haradan)'],
    ['bestehen', 'aus', 'Dativ', 'təşkil olmaq'],
    ['aussteigen', 'aus', 'Dativ', 'düşmək (nəydənsə)'],
    ['träumen', 'von', 'Dativ', 'arzu etmək'],
    ['erzählen', 'von', 'Dativ', 'danışmaq'],
    ['halten', 'von', 'Dativ', 'fikir'],
    ['abhängen', 'von', 'Dativ', 'asılı olmaq'],
    ['bitten', 'um', 'Akkusativ', 'xahiş etmək'],
    ['gehen', 'um', 'Akkusativ', 'getmək (ətrafında)'],
    ['sich kümmern', 'um', 'Akkusativ', 'qayğı göstərmək'],
    ['kämpfen', 'um', 'Akkusativ', 'mübarizə etmək'],
    ['fürchten', 'um', 'Akkusativ', 'narahat olmaq'],
    ['sein', 'gegen', 'Akkusativ', 'qarşı olmaq'],
    ['kämpfen', 'gegen', 'Akkusativ', 'mübarizə etmək'],
    ['protestieren', 'gegen', 'Akkusativ', 'etiraz etmək'],
    ['leben', 'ohne', 'Akkusativ', 'yaşamaq (olmayan)'],
    ['gehen', 'bis', 'Akkusativ', 'getmək (qədər)'],
    ['denken', 'an', 'Akkusativ', 'düşünmək'],
    ['glauben', 'an', 'Akkusativ', 'inancı olmaq'],
    ['teilnehmen', 'an', 'Dativ', 'iştirak etmək'],
    ['schreiben', 'an', 'Akkusativ', 'yazmaq'],
    ['wohnen', 'in', 'Dativ', 'yaşamaq'],
    ['arbeiten', 'in', 'Dativ', 'işləmək'],
    ['warten', 'auf', 'Akkusativ', 'gözləmək'],
    ['hoffen', 'auf', 'Akkusativ', 'ümid etmək'],
    ['sprechen', 'über', 'Akkusativ', 'danışmaq'],
    ['fragen', 'nach', 'Dativ', 'soruşmaq'],
    ['suchen', 'nach', 'Dativ', 'axtarmaq'],
    ['Angst haben', 'vor', 'Dativ', 'qorxmaq'],
    ['warnen', 'vor', 'Dativ', 'xəbərdar etmək'],
    ['sitzen', 'gegenüber', 'Dativ', 'oturmaq (qarşıda)'],
    ['sich entscheiden', 'für', 'Akkusativ', 'qərar vermək'],
    ['sich interessieren', 'für', 'Akkusativ', 'maraqlanmaq'],
    ['sorgen', 'für', 'Akkusativ', 'qayğı göstərmək'],
    ['halten', 'für', 'Akkusativ', 'saxlamaq (nəyəsə)'],
    ['danken', 'für', 'Akkusativ', 'təşəkkür etmək'],
    ['sich bedanken', 'für', 'Akkusativ', 'təşəkkür etmək'],
    ['sich vorbereiten', 'auf', 'Akkusativ', 'hazırlaşmaq'],
    ['sich freuen', 'auf', 'Akkusativ', 'sevinmək'],
    ['achten', 'auf', 'Akkusativ', 'diqqət etmək'],
    ['verzichten', 'auf', 'Akkusativ', 'vaz keçmək'],
    ['antworten', 'auf', 'Akkusativ', 'cavab vermək'],
    ['reagieren', 'auf', 'Akkusativ', 'reaksiya göstərmək'],
    ['bestehen', 'auf', 'Dativ', 'israrlı olmaq'],
    ['gehen', 'zu', 'Dativ', 'getmək'],
    ['kommen', 'zu', 'Dativ', 'gəlmək'],
    ['gehören', 'zu', 'Dativ', 'aid olmaq'],
    ['sagen', 'zu', 'Dativ', 'demək'],
    ['meinen', 'zu', 'Dativ', 'fikir bildirmək'],
    ['raten', 'zu', 'Dativ', 'məsləhət vermək'],
    ['anfangen', 'mit', 'Dativ', 'başlamaq'],
    ['aufhören', 'mit', 'Dativ', 'dayandırmaq'],
    ['rechnen', 'mit', 'Dativ', 'güman etmək'],
    ['streiten', 'mit', 'Dativ', 'dalaşmaq'],
    ['helfen', 'bei', 'Dativ', 'kömək etmək'],
    ['ankommen', 'in', 'Dativ', 'gəlmək'],
    ['wohnen', 'in', 'Dativ', 'yaşamaq'],
    ['arbeiten', 'in', 'Dativ', 'işləmək'],
    ['bestehen', 'aus', 'Dativ', 'təşkil olmaq'],
    ['kommen', 'aus', 'Dativ', 'gəlmək'],
    ['aussteigen', 'aus', 'Dativ', 'düşmək'],
    ['einsteigen', 'in', 'Akkusativ', 'minmək'],
    ['bitten', 'um', 'Akkusativ', 'xahiş etmək'],
    ['sich kümmern', 'um', 'Akkusativ', 'qayğı göstərmək'],
    ['fürchten', 'um', 'Akkusativ', 'narahat olmaq'],
    ['sein', 'gegen', 'Akkusativ', 'qarşı olmaq'],
    ['leben', 'ohne', 'Akkusativ', 'yaşamaq (olmayan)'],
    ['Angst haben', 'vor', 'Dativ', 'qorxmaq'],
    ['warnen', 'vor', 'Dativ', 'xəbərdar etmək'],
    ['sich erinnern', 'an', 'Akkusativ', 'xatırlamaq'],
    ['teilnehmen', 'an', 'Dativ', 'iştirak etmək'],
    ['schreiben', 'an', 'Akkusativ', 'yazmaq'],
    ['arbeiten', 'an', 'Dativ', 'işləmək (nəyəsə)'],
    ['sterben', 'an', 'Dativ', 'ölmək'],
    ['erkranken', 'an', 'Dativ', 'xəstələnmək'],
    ['legen', 'auf', 'Akkusativ', 'qoymaq'],
    ['sich konzentrieren', 'auf', 'Akkusativ', 'cəmləşmək'],
    ['sich spezialisieren', 'auf', 'Akkusativ', 'ixtisaslaşmaq'],
    ['sich verlieben', 'in', 'Akkusativ', 'aşiq olmaq'],
    ['teilen', 'in', 'Akkusativ', 'bölmək'],
    ['sich irren', 'in', 'Dativ', 'səhv etmək'],
    ['sich beschweren', 'bei', 'Dativ', 'şikayət etmək'],
    ['sich bedanken', 'bei', 'Dativ', 'təşəkkür etmək'],
    ['sich beschweren', 'über', 'Akkusativ', 'şikayət etmək'],
    ['sich ärgern', 'über', 'Akkusativ', 'əsəbləşmək'],
    ['weinen', 'über', 'Akkusativ', 'ağlamaq'],
    ['wissen', 'von', 'Dativ', 'bilmək'],
    ['hören', 'von', 'Dativ', 'eşitmək'],
    ['lesen', 'von', 'Dativ', 'oxumaq'],
    ['träumen', 'von', 'Dativ', 'arzu etmək'],
    ['erzählen', 'von', 'Dativ', 'danışmaq'],
    ['halten', 'von', 'Dativ', 'fikirdə olmaq'],
    ['abhängen', 'von', 'Dativ', 'asılı olmaq']
  ]
  },
  A2: {
    nouns: [
      ['Die', 'Erfahrung', 'Təcrübə'],
      ['Die', 'Umwelt', 'Ətraf mühit'],
      ['Die', 'Entscheidung', 'Qərar'],
      ['Der', 'Unterschied', 'Fərq'],
      ['Der', 'Erfolg', 'Uğur'],
      ['Die', 'Gesellschaft', 'Cəmiyyət'],
      ['Der', 'Beruf', 'Peşə'],
      ['Die', 'Karriere', 'Karera'],
      ['Das', 'Büro', 'Ofis'],
      ['Die', 'Beförderung', 'Yüksəliş'],
      ['Die', 'Stelle', 'Vəzifə'],
      ['Der', 'Arbeitsplatz', 'İş yeri'],
      ['Das', 'Unternehmen', 'Müəssisə'],
      ['Die', 'Konferenz', 'Konfrans'],
      ['Das', 'Meeting', 'Görüş'],
      ['Der', 'Kunde', 'Müştəri'],
      ['Das', 'Projekt', 'Layihə'],
      ['Die', 'Deadline', 'Son tarix'],
      ['Die', 'Lösung', 'Həll'],
      ['Der', 'Umweltschutz', 'Ətraf mühitin mühafizəsi'],
      ['Die', 'Verschmutzung', 'Çirklənmə'],
      ['Das', 'Klima', 'İqlim'],
      ['Die', 'Energie', 'Enerji'],
      ['Der', 'Müll', 'Zibil'],
      ['Das', 'Recycling', 'Təkrar emal'],
      ['Die', 'Pflanze', 'Bitki'],
      ['Das', 'Gefühl', 'Hiss'],
      ['Die', 'Trauer', 'Kədər'],
      ['Die', 'Wut', 'Hirs'],
      ['Die', 'Enttäuschung', 'Ümid qırıqlığı'],
      ['Der', 'Stolz', 'Qürur'],
      ['Die', 'Scham', 'Utanç'],
      ['Der', 'Neid', 'Paxıllıq'],
      ['Die', 'Geduld', 'Səbir'],
      ['Der', 'Vorteil', 'Üstünlük'],
      ['Der', 'Nachteil', 'Çatışmazlıq'],
      ['Die', 'Meinung', 'Fikir'],
      ['Die', 'Diskussion', 'Müzakirə'],
      ['Der', 'Konflikt', 'Konflikt'],
      ['Die', 'Zusammenarbeit', 'Əməkdaşlıq'],
      ['Der', 'Fortschritt', 'Tərəqqi'],
      ['Die', 'Entwicklung', 'İnkişaf'],
      ['Die', 'Wahrscheinlichkeit', 'Ehtimal'],
      ['Der', 'Einfluss', 'Təsir'],
      ['Die', 'Verantwortung', 'Məsuliyyət'],
      ['Die', 'Freiheit', 'Azadlıq'],
      ['Die', 'Gerechtigkeit', 'Ədalət'],
      ['Die', 'Tradition', 'Ənənə'],
      ['Die', 'Generation', 'Nəsil'],
      ['Die', 'Zukunft', 'Gələcək'],
      ['Die', 'Vergangenheit', 'Keçmiş'],
      ['Die', 'Gegenwart', 'İndiki zaman'],
      ['Der', 'Vergleich', 'Müqayisə'],
      ['Die', 'Bedingung', 'Şərt'],
      ['Der', 'Zweifel', 'Şübhə'],
      ['Die', 'Gewohnheit', 'Vərdiş'],
      ['Der', 'Charakter', 'Xarakter'],
      ['Die', 'Persönlichkeit', 'Şəxsiyyət'],
      ['Das', 'Verhalten', 'Davranış'],
      ['Die', 'Beziehung', 'Münasibət'],
      ['Die', 'Nachricht', 'Xəbər'],
      ['Das', 'Ereignis', 'Hadisə'],
      ['Die', 'Erinnerung', 'Xatirə'],
      ['Der', 'Traum', 'Yuxu / Arzu'],
      ['Die', 'Realität', 'Reallıq'],
      ['Die', 'Wahrheit', 'Həqiqət'],
      ['Der', 'Irrtum', 'Səhv'],
      ['Die', 'Kritik', 'Tənqid'],
      ['Das', 'Lob', 'Tərif'],
      ['Der', 'Rat', 'Məsləhət'],
      ['Die', 'Hilfe', 'Kömək'],
      ['Der', 'Vorschlag', 'Təklif'],
      ['Die', 'Annahme', 'Qəbul / Fərziyyə'],
      ['Der', 'Vertrag', 'Müqavilə'],
      ['Die', 'Vereinbarung', 'Razılaşma'],
      ['Das', 'Ziel', 'Hədəf'],
      ['Der', 'Weg', 'Yol'],
      ['Die', 'Methode', 'Üsul'],
      ['Der', 'Versuch', 'Cəhd'],
      ['Das', 'Risiko', 'Risk'],
      ['Die', 'Chance', 'Şans'],
      ['Der', 'Zufall', 'Təsadüf'],
      ['Die', 'Situation', 'Vəziyyət'],
      ['Der', 'Zustand', 'Vəziyyət'],
      ['Die', 'Änderung', 'Dəyişiklik'],
      ['Der', 'Wechsel', 'Dəyişmə'],
      ['Die', 'Wirkung', 'Təsir'],
      ['Der', 'Grund', 'Səbəb'],
      ['Die', 'Folge', 'Nəticə'],
      ['Das', 'Angebot', 'Təklif'],
      ['Die', 'Nachfrage', 'Tələb'],
      ['Der', 'Markt', 'Bazar'],
      ['Die', 'Konkurrenz', 'Rəqabət'],
      ['Der', 'Gewinn', 'Qazanç'],
      ['Der', 'Verlust', 'İtki'],
      ['Die', 'Kosten', 'Xərclər'],
      ['Das', 'Budget', 'Büdcə'],
      ['Die', 'Investition', 'İnvestisiya'],
      ['Der', 'Kredit', 'Kredit'],
      ['Die', 'Schuld', 'Borç'],
      ['Der', 'Betrag', 'Məbləğ'],
      ['Die', 'Rechnung', 'Hesab'],
      ['Das', 'Formular', 'Forma'],
      ['Die', 'Bewerbung', 'Müraciət'],
      ['Das', 'Vorstellungsgespräch', 'Müsahibə'],
      ['Die', 'Qualifikation', 'İxtisas'],
      ['Die', 'Weiterbildung', 'Təkmilləşmə'],
      ['Der', 'Abschluss', 'Bitmə / Diplom'],
      ['Die', 'Ausbildung', 'Təlim'],
      ['Der', 'Praktikant', 'Təcrübəçi'],
      ['Die', 'Praktikantin', 'Təcrübəçi (qadın)'],
      ['Die', 'Branche', 'Sahə'],
      ['Der', 'Sektor', 'Sektor'],
      ['Die', 'Wirtschaft', 'İqtisadiyyat'],
      ['Das', 'Wachstum', 'Artım'],
      ['Die', 'Krise', 'Böhran'],
      ['Der', 'Rückgang', 'Azalma'],
      ['Die', 'Steigerung', 'Artım'],
      ['Der', 'Durchschnitt', 'Orta'],
      ['Die', 'Statistik', 'Statistika'],
      ['Die', 'Forschung', 'Tədqiqat'],
      ['Die', 'Wissenschaft', 'Elm'],
      ['Das', 'Experiment', 'Eksperiment'],
      ['Die', 'Entdeckung', 'Kəşf'],
      ['Die', 'Erfindung', 'İxtira'],
      ['Der', 'Fortschritt', 'Tərəqqi'],
      ['Die', 'Technologie', 'Texnologiya'],
      ['Das', 'Verfahren', 'Üsul'],
      ['Die', 'Umweltverschmutzung', 'Ətraf mühitin çirklənməsi'],
      ['Der', 'Klimawandel', 'İqlim dəyişikliyi'],
      ['Die', 'Nachhaltigkeit', 'Davamlılıq'],
      ['Die', 'Ressource', 'Ehtiyat'],
      ['Der', 'Verbrauch', 'İstifadə'],
      ['Die', 'Ersparnis', 'Qənaət'],
      ['Das', 'Bewusstsein', 'Şüur'],
      ['Die', 'Einstellung', 'Münasibət / Baxış']
    ],
    verbsWithPrepositions: [
      ['sich gewöhnen', 'an', 'Akkusativ', 'öyrəşmək'],
      ['verzichten', 'auf', 'Akkusativ', 'vaz keçmək'],
      ['aufpassen', 'auf', 'Akkusativ', 'diqqət etmək'],
      ['achten', 'auf', 'Akkusativ', 'diqqət etmək'],
      ['sich konzentrieren', 'auf', 'Akkusativ', 'cəmləşmək'],
      ['sich vorbereiten', 'auf', 'Akkusativ', 'hazırlaşmaq'],
      ['sich freuen', 'auf', 'Akkusativ', 'sevinmək'],
      ['reagieren', 'auf', 'Akkusativ', 'reaksiya göstərmək'],
      ['antworten', 'auf', 'Akkusativ', 'cavab vermək'],
      ['bestehen', 'aus', 'Dativ', 'təşkil olmaq'],
      ['teilnehmen', 'an', 'Dativ', 'iştirak etmək'],
      ['abhängen', 'von', 'Dativ', 'asılı olmaq'],
      ['sprechen', 'mit', 'Dativ', 'danışmaq'],
      ['sich beschweren', 'über', 'Akkusativ', 'şikayət etmək'],
      ['sich ärgern', 'über', 'Akkusativ', 'əsəbləşmək'],
      ['nachdenken', 'über', 'Akkusativ', 'düşünmək'],
      ['sorgen', 'für', 'Akkusativ', 'qayğı göstərmək'],
      ['sich interessieren', 'für', 'Akkusativ', 'maraqlanmaq'],
      ['halten', 'von', 'Dativ', 'fikirdə olmaq'],
      ['träumen', 'von', 'Dativ', 'arzu etmək'],
      ['wissen', 'von', 'Dativ', 'bilmək'],
      ['gehen', 'zu', 'Dativ', 'getmək'],
      ['kommen', 'zu', 'Dativ', 'gəlmək'],
      ['führen', 'zu', 'Dativ', 'səbəb olmaq'],
      ['beitragen', 'zu', 'Dativ', 'töhfə vermək'],
      ['anfangen', 'mit', 'Dativ', 'başlamaq'],
      ['aufhören', 'mit', 'Dativ', 'dayandırmaq'],
      ['rechnen', 'mit', 'Dativ', 'güman etmək'],
      ['helfen', 'bei', 'Dativ', 'kömək etmək'],
      ['ankommen', 'in', 'Dativ', 'gəlmək'],
      ['wohnen', 'in', 'Dativ', 'yaşamaq'],
      ['einsteigen', 'in', 'Akkusativ', 'minmək'],
      ['sich verlieben', 'in', 'Akkusativ', 'aşiq olmaq'],
      ['bestehen', 'auf', 'Dativ', 'israrlı olmaq'],
      ['bitten', 'um', 'Akkusativ', 'xahiş etmək'],
      ['sich kümmern', 'um', 'Akkusativ', 'qayğı göstərmək'],
      ['fürchten', 'um', 'Akkusativ', 'narahat olmaq'],
      ['Angst haben', 'vor', 'Dativ', 'qorxmaq'],
      ['warnen', 'vor', 'Dativ', 'xəbərdar etmək'],
      ['sich erinnern', 'an', 'Akkusativ', 'xatırlamaq'],
      ['denken', 'an', 'Akkusativ', 'düşünmək'],
      ['glauben', 'an', 'Akkusativ', 'inancı olmaq'],
      ['schreiben', 'an', 'Akkusativ', 'yazmaq'],
      ['arbeiten', 'an', 'Dativ', 'işləmək (nəyəsə)'],
      ['sich gewöhnen', 'an', 'Akkusativ', 'öyrəşmək'],
      ['sich anpassen', 'an', 'Akkusativ', 'uyğunlaşmaq'],
      ['sich beteiligen', 'an', 'Dativ', 'iştirak etmək'],
      ['zweifeln', 'an', 'Dativ', 'şübhə etmək'],
      ['sich gewöhnen', 'an', 'Akkusativ', 'alışmaq'],
      ['verzichten', 'auf', 'Akkusativ', 'vaz keçmək'],
      ['aufpassen', 'auf', 'Akkusativ', 'diqqət etmək (nəyəsə)'],
      ['hoffen', 'auf', 'Akkusativ', 'ümid etmək'],
      ['warten', 'auf', 'Akkusativ', 'gözləmək'],
      ['sich verlassen', 'auf', 'Akkusativ', 'etibar etmək'],
      ['hinweisen', 'auf', 'Akkusativ', 'işarə etmək'],
      ['reagieren', 'auf', 'Akkusativ', 'reaksiya göstərmək'],
      ['sich spezialisieren', 'auf', 'Akkusativ', 'ixtisaslaşmaq'],
      ['bestehen', 'aus', 'Dativ', 'təşkil olmaq'],
      ['bestehen', 'in', 'Dativ', 'olmaq (nəyəsə)'],
      ['sich irren', 'in', 'Dativ', 'səhv etmək']
    ]
  }
};
