-- Artikel Match: uzaq sinxron (opsional). Cədvəl yoxdursa tətbiq localStorage ilə işləməyə davam edir.
create table if not exists public.user_progress (
  id bigint generated by default as identity primary key,
  device_id text not null,
  word_id text not null,
  level text not null,
  status text not null check (status in ('hard', 'mastered', 'review')),
  updated_at timestamptz not null default now(),
  unique (device_id, word_id)
);

create index if not exists user_progress_device_id_idx on public.user_progress (device_id);

-- İnkişaf üçün: öz RLS siyasətlərinizi əlavə edin (auth.users ilə bağlamaq tövsiyə olunur).
alter table public.user_progress disable row level security;
